Feature/PF-224-empleadosBE
LCampi01/garbi-front pull request #39
Opened 2024-08-08 22:00 UTC by SantiagoOrlando29

2024-08-09 11:24 UTC, NachoTRD requested changes

2024-08-09 11:24 UTC, NachoTRD commented on src/api/hooks/useEmployees/request.js
> +  const generateRandomPassword = (length) => {
Toda la logica tiene que estar en el BE

2024-08-09 11:24 UTC, NachoTRD commented on src/forms/CreateEmployee/CreateEmployeeForm.jsx
> +        companyId: '6642c093eb730d1cd07762b0', //TODO: get it from the current user
hay en el proyecto un deserializador de json, y esta guardado el token en el local storage. creo que para el login lo use

2024-08-09 11:24 UTC, NachoTRD commented on src/forms/CreateEmployee/CreateEmployeeForm.jsx
> +        companyId: '6642c093eb730d1cd07762b0', //TODO: get it from the current user
deserializador de token* perdon

2024-08-09 13:54 UTC, SantiagoOrlando29 commented on src/api/hooks/useEmployees/request.js
> +  const generateRandomPassword = (length) => {
eliminado

2024-08-09 13:54 UTC, SantiagoOrlando29 commented on src/forms/CreateEmployee/CreateEmployeeForm.jsx
> +        companyId: '6642c093eb730d1cd07762b0', //TODO: get it from the current user
listo. graciasss

2024-08-10 13:09 UTC, NachoTRD approved these changes

2024-08-10 13:09 UTC, merged