Feature/PF-271-modalReports
LCampi01/garbi-front pull request #47
Opened 2024-09-01 18:38 UTC by SantiagoOrlando29

2024-09-01 21:44 UTC, NachoTRD commented on src/components/ReportStatusSelect/ReportStatusSelect.jsx
> +        width: '144px',
Pongamos un width 100% y que el contenedor de este componente defina el width.

2024-09-01 21:49 UTC, NachoTRD requested changes

2024-09-01 21:49 UTC, NachoTRD commented on src/components/ReportStatusSelect/ReportStatusSelect.jsx
> +            color: selectedValue === 'NUEVO' ? estados['NUEVO'].colorText : 'inherit',
Lo mismo que el comentario de arriba

2024-09-01 21:49 UTC, NachoTRD commented on src/components/ReportStatusSelect/ReportStatusSelect.jsx
> +    if (newValue === 'RECHAZADO') {
Que te parece reemplazar el string directamente por el string que ya tiene el objeto estados . seria algo como estados.nuevo.text === selectedValue

2024-09-02 03:41 UTC, SantiagoOrlando29 commented on src/components/ReportStatusSelect/ReportStatusSelect.jsx
> +        width: '144px',
listo. le modifiqué en la tabla de reportes el width de esa celda (y de otras) así quedaba bien. probé el responsive de toda esa tabla y para mi quedó bien

2024-09-03 00:28 UTC, NachoTRD approved these changes

2024-09-03 00:28 UTC, merged