Feature/PF-303-searcher y button y empleados y etc
LCampi01/garbi-front pull request #75
Opened 2024-09-22 03:33 UTC by SantiagoOrlando29

2024-09-22 17:29 UTC, NachoTRD requested changes

2024-09-22 17:29 UTC, NachoTRD commented on src/components/CommonTableList/CommonTableList.jsx
> +      <ModalCreateResource
No me parece copado tener los modales aca porque no responsabilidad de CommonListTable tener los modales adentro. Podriamos poner los modales junto al FiltersideComponent

2024-09-22 17:29 UTC, NachoTRD commented on src/components/SearcherPaginated/SearcherPaginated.jsx
> +  selectedElement, handleOpenModifyElementModal, handleOpenDeleteElementModal
Vamos a hacer algo mejor porque ya hay demasiadas props. vamos a reducir todo a una prop que sea algo como: componentToRender, que va a ir ese lugar donde va el date picker o el boton.

2024-09-22 17:29 UTC, NachoTRD commented on src/components/SearcherPaginated/SearcherPaginated.jsx
> +          <Box>
Extraer a un componente algo como EditAndDeleteButtons o algo asi

2024-09-22 17:29 UTC, NachoTRD commented on src/components/CommonTableList/CommonTableList.jsx
> +  modifyModalTitle, ModifyForm,
aca vamos a recibir el componente que le vamos a pasar al SearcherPaginated

2024-09-22 17:29 UTC, NachoTRD commented on src/pages/Containers/ContainerPage.jsx
> +              reloadTable={reloadTable}
aca vamos a hacer algo como
componentToRender = { <EditAndDeleteButtons onEditClick={openEditModal) ... />}
y este componentToRender va derecho al searcherPaginated...

Con esto ya llenamos las props desde antes de mandarlo y nos evitamos pasar tantas props 


cuando tengamos que usar un DatePicker seria algo como

componentToRender = {<DatePicker ...props />

2024-09-22 17:29 UTC, NachoTRD commented on src/pages/Company/CompanyPage.jsx
> +          button={true}
Los booleanos los sacamos por el componentToRender

2024-09-22 17:29 UTC, NachoTRD commented on src/components/CommonTableList/CommonTableList.jsx
> +  useEffect(() => { //to reload table when a new row is added.
No soy muy fanatico de esta solución para recargar la tabla pero banco la creatividad jajajaj por ahora vamos a dejarlo asi pero despues veamos de darle una vuelta de rosca para que quede mas claro

2024-09-23 19:58 UTC, SantiagoOrlando29 commented on src/components/SearcherPaginated/SearcherPaginated.jsx
> +  selectedElement, handleOpenModifyElementModal, handleOpenDeleteElementModal
no se si entendi 100% asiq fijate cuando pusheo

2024-09-23 20:10 UTC, SantiagoOrlando29 commented on src/components/SearcherPaginated/SearcherPaginated.jsx
> +          <Box>
para? se usan en algún otro lado?

2024-09-23 21:48 UTC, NachoTRD commented on src/pages/Containers/ContainerPage.jsx
> +                <TableButtons
SEXOOOOOOOOOOOOOOOOOO

2024-09-23 21:49 UTC, NachoTRD reviewed
EXCELENTE 👨🏻‍🚀🚀 👏🏻👏🏻👏🏻👏🏻

2024-09-24 00:17 UTC, merged